# Generated by Django 5.2.17 on 2026-09-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('entidad', models.CharField(max_length=50, verbose_name='entidad')),
                ('entidad_id', models.BigIntegerField(blank=True, null=True, verbose_name='entidad_id')),
                ('accion', models.CharField(max_length=30, verbose_name='accion')),
                ('datos_antes', models.JSONField(blank=True, null=True, verbose_name='datos_antes')),
                ('datos_despues', models.JSONField(blank=True, null=True, verbose_name='datos_despues')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-id'],
            },
        ),
    ]
