# Generated by Django 5.2.17 on 2026-09-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disponibilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('tema', models.CharField(max_length=200, verbose_name='tema')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA_ESTUDIANTE', 'Cancelada por estudiante'), ('CANCELADA_DOCENTE', 'Cancelada por docente'), ('NO_ASISTIO', 'No asistió')], default='RESERVADA', max_length=25, verbose_name='estado')),
                ('asistencia', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('ASISTIO_TARDE', 'Asistió tarde'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=20, verbose_name='asistencia')),
                ('minutos_retraso', models.SmallIntegerField(default=0, verbose_name='minutos_retraso')),
                ('hora_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='hora_inicio_real')),
                ('hora_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='hora_fin_real')),
                ('notas_docente', models.TextField(blank=True, null=True, verbose_name='notas_docente')),
                ('compromisos', models.TextField(blank=True, null=True, verbose_name='compromisos')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorias', to='disponibilidad.bloquedisponibilidad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorias', to=settings.AUTH_USER_MODEL)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutoría',
                'verbose_name_plural': 'Tutorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('calificacion', models.SmallIntegerField(verbose_name='calificacion')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='comentario')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tutoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='tutorias.tutoria')),
            ],
            options={
                'verbose_name': 'Evaluación de tutoría',
                'verbose_name_plural': 'Evaluaciones de tutorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('origen', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='origen')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('horas_previas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='horas_previas')),
                ('penalizada', models.BooleanField(default=False, verbose_name='penalizada')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones', to=settings.AUTH_USER_MODEL)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tutoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones', to='tutorias.tutoria')),
            ],
            options={
                'verbose_name': 'Cancelación',
                'verbose_name_plural': 'Cancelaciones',
                'ordering': ['id'],
            },
        ),
    ]
