# Generated by Django 5.2.17 on 2026-09-21 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
        ('tutorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tutoria',
            index=models.Index(fields=['estudiante', 'estado'], name='idx_tutoria_estudiante'),
        ),
        migrations.AddIndex(
            model_name='tutoria',
            index=models.Index(fields=['bloque'], name='idx_tutoria_bloque'),
        ),
        migrations.AddConstraint(
            model_name='tutoria',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['RESERVADA', 'CONFIRMADA', 'EN_CURSO'])), fields=('bloque', 'estudiante'), name='ux_tutoria_activa'),
        ),
        migrations.AddConstraint(
            model_name='tutoria',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_retraso__gte', 0)), name='ck_tutoria_retraso'),
        ),
    ]
