# Generated by Django 5.2.17 on 2026-09-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora_inicio', models.TimeField(verbose_name='hora_inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora_fin')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=11, verbose_name='modalidad')),
                ('lugar', models.CharField(blank=True, max_length=150, null=True, verbose_name='lugar')),
                ('enlace_virtual', models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace_virtual')),
                ('cupo_total', models.SmallIntegerField(default=1, verbose_name='cupo_total')),
                ('cupo_ocupado', models.SmallIntegerField(default=0, verbose_name='cupo_ocupado')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('COMPLETO', 'Completo'), ('CANCELADO', 'Cancelado'), ('CERRADO', 'Cerrado')], default='DISPONIBLE', max_length=10, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades', to='catalogo.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_disponibilidad', to='catalogo.periodoacademico')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloque de disponibilidad',
                'verbose_name_plural': 'Bloques de disponibilidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('dia_semana', models.SmallIntegerField(verbose_name='dia_semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora_inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora_fin')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=11, verbose_name='modalidad')),
                ('lugar', models.CharField(blank=True, max_length=150, null=True, verbose_name='lugar')),
                ('enlace_virtual', models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace_virtual')),
                ('cupo_total', models.SmallIntegerField(default=1, verbose_name='cupo_total')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_disponibilidad', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_disponibilidad', to='catalogo.periodoacademico')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de disponibilidad',
                'verbose_name_plural': 'Plantillas de disponibilidad',
                'ordering': ['id'],
            },
        ),
    ]
